services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./db.local:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kawara
  kawara:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
